import{a as d,S as w,i}from"./assets/vendor-CNqCr-V-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const S="53269765-cd39f78e40f469f4b1e9f0733",P="https://pixabay.com/api/";d.defaults.baseURL=P;async function q(t,o){return(await d.get("",{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".load-more");let c;function v(t){const o=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:a,comments:b,downloads:L})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
          </a>

          <ul class="info">
            <li><b>Likes</b> ${r}</li>
            <li><b>Views</b> ${a}</li>
            <li><b>Comments</b> ${b}</li>
            <li><b>Downloads</b> ${L}</li>
          </ul>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",o),c?c.refresh():c=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function R(){f.innerHTML=""}function B(){m.classList.remove("boost")}function u(){m.classList.add("boost")}function E(){g.classList.remove("boost")}function y(){g.classList.add("boost")}const $=document.querySelector(".form"),M=document.querySelector(".load-more");let h="",l=1;const x=15;$.addEventListener("submit",O);M.addEventListener("click",A);async function O(t){t.preventDefault();const o=t.currentTarget.elements["search-text"].value.trim();if(!o){i.warning({message:"Please enter a search query 🙂",position:"topRight"});return}h=o,l=1,R(),y(),p(!1)}function A(){l+=1,p(!0)}async function p(t){B();try{const o=await q(h,l),{hits:s,totalHits:n}=o;if(u(),!s.length&&!t){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(s);const e=Math.ceil(n/x);l<e?E():(y(),t&&i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),t&&_()}catch{u(),i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}}function _(){var s,n;const t=(n=(s=document.querySelector(".gallery"))==null?void 0:s.firstElementChild)==null?void 0:n.getBoundingClientRect();if(!t)return;const o=t.height||t.bottom-t.top;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
